"""
tools/env_manager.py - Proactive .env manager
"""
import re
import os
from pathlib import Path
from typing import Dict, List
from core.logger import logger, console
from rich.panel import Panel

ENV_REGISTRY = {
    "SOLANA_PRIVATE_KEY":        ("Private key wallet Solana (base58)", "5xK...abc"),
    "WALLET_PRIVATE_KEY":        ("Private key wallet Solana (base58)", "5xK...abc"),
    "SOLANA_RPC_URL":            ("Solana RPC endpoint", "https://api.mainnet-beta.solana.com"),
    "SOLANA_WS_URL":             ("Solana WebSocket endpoint", "wss://api.mainnet-beta.solana.com"),
    "HELIUS_API_KEY":            ("Helius RPC API key (opsional)", "abc123..."),
    "PAPER_TRADING":             ("Paper trading mode (true=simulasi)", "true"),
    "LIVE_TRADING":              ("Live trading (false untuk safety)", "false"),
    "DEFAULT_POSITION_SIZE_SOL": ("Ukuran posisi default SOL", "0.1"),
    "MAX_DAILY_LOSS_SOL":        ("Maksimum loss harian SOL", "1.0"),
    "STOP_LOSS_PERCENT":         ("Stop loss percentage", "10"),
    "TAKE_PROFIT_MULTIPLIER":    ("Take profit multiplier", "2.0"),
    "SLIPPAGE_BPS":              ("Slippage basis points", "100"),
    "YOUTUBE_API_KEY":           ("YouTube Data API v3 key", "AIza..."),
    "GOOGLE_CLIENT_ID":          ("Google OAuth client ID", "xxx.apps.googleusercontent.com"),
    "GOOGLE_CLIENT_SECRET":      ("Google OAuth client secret", "GOCSPX-..."),
    "OPENAI_API_KEY":            ("OpenAI API key", "sk-..."),
    "OPENROUTER_API_KEY":        ("OpenRouter API key", "sk-or-..."),
    "ANTHROPIC_API_KEY":         ("Anthropic Claude API key", "sk-ant-..."),
    "TELEGRAM_BOT_TOKEN":        ("Telegram bot token dari @BotFather", "123456:ABC..."),
    "TELEGRAM_CHAT_ID":          ("Telegram chat/channel ID", "-100123456"),
    "DISCORD_WEBHOOK_URL":       ("Discord webhook URL", "https://discord.com/api/webhooks/..."),
    "SECRET_KEY":                ("Secret key aplikasi", "random-32-chars"),
    "API_KEY":                   ("API key", "your-api-key"),
    "API_SECRET":                ("API secret", "your-api-secret"),
}

SKIP_IF_HAS_DEFAULT = {
    "PAPER_TRADING", "LIVE_TRADING", "DEFAULT_POSITION_SIZE_SOL",
    "MAX_DAILY_LOSS_SOL", "STOP_LOSS_PERCENT", "TAKE_PROFIT_MULTIPLIER",
    "SLIPPAGE_BPS", "SOLANA_RPC_URL",
}

class EnvManager:
    def scan_required_vars(self, project_dir: str) -> List[str]:
        pd = Path(project_dir)
        found = set()
        pattern = re.compile(r'os\.getenv\(["\']([A-Z_][A-Z0-9_]*)["\']')
        for py_file in pd.rglob("*.py"):
            try:
                text = py_file.read_text(encoding="utf-8", errors="ignore")
                found.update(pattern.findall(text))
            except Exception:
                pass
        return sorted(found)

    def read_env_file(self, env_path: Path) -> Dict[str, str]:
        result = {}
        if not env_path.exists():
            return result
        for line in env_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                result[k.strip()] = v.strip()
        return result

    def write_env_file(self, env_path: Path, env_dict: Dict[str, str]):
        lines = []
        if env_path.exists():
            existing_lines = env_path.read_text(encoding="utf-8").splitlines()
            written_keys = set()
            for line in existing_lines:
                stripped = line.strip()
                if stripped and not stripped.startswith("#") and "=" in stripped:
                    k = stripped.split("=")[0].strip()
                    if k in env_dict:
                        lines.append(f"{k}={env_dict[k]}")
                        written_keys.add(k)
                    else:
                        lines.append(line)
                else:
                    lines.append(line)
            new_keys = set(env_dict.keys()) - written_keys
            if new_keys:
                lines.append("")
                lines.append("# Added by AgentJW")
                for k in sorted(new_keys):
                    lines.append(f"{k}={env_dict[k]}")
        else:
            lines.append("# Generated by AgentJW")
            for k, v in env_dict.items():
                lines.append(f"{k}={v}")
        env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    def check_and_prompt(self, project_dir: str, project_name: str = "") -> Dict[str, str]:
        pd = Path(project_dir)
        env_path = pd / ".env"
        required = self.scan_required_vars(project_dir)
        existing = self.read_env_file(env_path)
        missing = [v for v in required if not existing.get(v) or existing.get(v) in ("", "your_key_here", "xxx", "CHANGE_ME")]
        if not missing:
            console.print("[green]✅ Semua env vars sudah terset![/green]")
            return {}
        console.print()
        console.print(Panel(
            f"[yellow]Project [bold]{project_name or pd.name}[/bold] butuh {len(missing)} konfigurasi.[/yellow]\n"
            "Tekan Enter untuk skip (pakai default).",
            title="🔑 Setup API Keys & Config", border_style="yellow"
        ))
        filled = {}
        critical = [v for v in missing if any(k in v for k in ["PRIVATE_KEY","SECRET","TOKEN","PASSWORD"])]
        optional = [v for v in missing if v not in critical]
        for var in critical + optional:
            info = ENV_REGISTRY.get(var, (f"Nilai untuk {var}", "your-value-here"))
            desc, example = info
            is_secret = any(k in var for k in ["KEY","SECRET","TOKEN","PASSWORD"])
            console.print(f"\n[cyan]📌 {var}[/cyan]")
            console.print(f"   [dim]{desc}[/dim]")
            if not is_secret:
                console.print(f"   [dim]Contoh: {example}[/dim]")
            try:
                value = input("   Masukkan nilai (Enter=skip): ").strip()
                if value:
                    filled[var] = value
                    existing[var] = value
                    console.print("   [green]✓ Disimpan[/green]")
                elif var in SKIP_IF_HAS_DEFAULT:
                    existing.setdefault(var, example)
                    console.print(f"   [dim]→ Pakai default: {example}[/dim]")
                else:
                    console.print("   [yellow]→ Dilewati (isi nanti)[/yellow]")
            except (EOFError, KeyboardInterrupt):
                continue
        self.write_env_file(env_path, existing)
        if filled:
            console.print(Panel(
                f"[green]✅ {len(filled)} variabel disimpan ke {env_path}[/green]\n"
                + "\n".join(f"  • {k}" for k in filled),
                title="💾 .env Updated", border_style="green"
            ))
        return filled

    def generate_env_template(self, project_dir: str) -> str:
        required = self.scan_required_vars(project_dir)
        existing = self.read_env_file(Path(project_dir) / ".env")
        lines = ["# .env — Generated by AgentJW", "# Paste nilai yang ⚠ ke chat", ""]
        for var in required:
            info = ENV_REGISTRY.get(var, (f"Nilai untuk {var}", "???"))
            desc, example = info
            current = existing.get(var, "")
            is_filled = bool(current) and current not in ("", "your_key_here", "xxx")
            status = "✓" if is_filled else "⚠"
            val_display = current if is_filled else f"???  # contoh: {example}"
            lines.append(f"# {status} {desc}")
            lines.append(f"{var}={val_display}")
            lines.append("")
        return "\n".join(lines)

env_manager = EnvManager()
